# Generated by Django 5.0.12 on 2025-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='value',
        ),
        migrations.AddField(
            model_name='specification',
            name='brand',
            field=models.CharField(default='Unknown', help_text='Enter the brand of the vehicle', max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='color',
            field=models.CharField(default='Unknown', help_text='Enter the color of the vehicle', max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='fuel',
            field=models.CharField(default='Unknown', help_text='Enter the fuel type of the vehicle', max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='model',
            field=models.CharField(default='Unknown', help_text='Enter the model of the vehicle', max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='year',
            field=models.IntegerField(default=2000, help_text='Enter the year of the vehicle'),
        ),
    ]
