# Generated by Django 5.0.12 on 2025-02-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_remove_specification_name_remove_specification_value_and_more'),
        ('vehicles', '0003_alter_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='specification',
            name='vehicle_plate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='vehicles.vehicle', to_field='plate'),
            preserve_default=False,
        ),
    ]
