# Generated by Django 5.0.12 on 2025-02-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0004_alter_specification_vehicle_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='vehicle_plate',
            new_name='plate',
        ),
    ]
