# Generated by Django 5.0.12 on 2025-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0005_rename_vehicle_plate_specification_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='color',
            field=models.CharField(blank=True, default='Unknown', help_text='Enter the color of the vehicle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='fuel',
            field=models.CharField(blank=True, default='Unknown', help_text='Enter the fuel type of the vehicle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='model',
            field=models.CharField(blank=True, default='Unknown', help_text='Enter the model of the vehicle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='year',
            field=models.IntegerField(blank=True, default=2000, help_text='Enter the year of the vehicle', null=True),
        ),
    ]
