# Generated by Django 5.0.12 on 2025-02-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0006_alter_specification_color_alter_specification_fuel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='year',
            new_name='first_registry',
        ),
    ]
