# Generated by Django 5.0.12 on 2025-02-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0009_remove_specification_id_alter_specification_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='color',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='first_registry',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='model',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='specification',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
