# Generated by Django 5.0.12 on 2025-02-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the vehicle', max_length=100)),
                ('year', models.IntegerField(help_text='The manufacturing year of the vehicle')),
                ('type', models.CharField(choices=[(None, 'Other'), ('CAR', 'Car'), ('MOTOR', 'Motor'), ('TRUCK', 'Truck')], help_text='The vehicle type', max_length=50, verbose_name='vehicle type')),
                ('owner', models.ForeignKey(help_text='The owner of the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='owners.owner')),
            ],
        ),
    ]
