# Generated by Django 5.0.12 on 2025-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', help_text='The plate of the vehicle', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[(None, 'Other'), ('CAR', 'Car'), ('MOTOR', 'Motor'), ('TRUCK', 'Truck')], default='CAR', help_text='The type of the vehicle', max_length=5),
        ),
    ]
