# Generated by Django 5.0.12 on 2025-02-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[(None, 'Other'), ('CAR', 'Car'), ('MOTOR', 'Motor'), ('TRUCK', 'Truck')], default='CAR', help_text='The type of the vehicle', max_length=5),
        ),
    ]
