# Generated by Django 5.0.12 on 2025-02-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('vehicles', '0007_alter_vehicle_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.OneToOneField(help_text='The owner of the vehicle', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(default='', help_text='The plate of the vehicle', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
